version: '2'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"
    networks:
      main:
        aliases:
          - web
  php:
    image: bytes85/php7.1-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000"
    networks:
      main:
        aliases:
          - php
  db:
    image: bytes85/mysql
    volumes:
     - /var/lib/mysql:/var/lib/mysql
    ports:
     - "3306:3306"
     - "4040:4040"
    environment:
     - MYSQL_DATABASE=critic
     - MYSQL_USER=mf
     - MYSQL_PASSWORD=maks
     - MYSQL_ROOT_PASSWORD=aqswdefr1
    networks:
      main:
        aliases:
          - db
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      main:
        aliases:
          - mailcatcher
networks:
  main:
