
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
	config.vm.network :forwarded_port, guest: 8000, host: 8000, auto_correct: true
	config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true
	config.vm.network "private_network", ip: "37.57.0.215"
	config.vm.synced_folder ".", "/var/www" 
	config.vm.box = "ubuntu/xenial64"
	config.vm.provision "shell" do |s|
		s.privileged = true
		s.path = "CriticSetup.sh"
	end
	
end